// ── Renderer: Standalone HTML report ────────────────────────────────────
//
// Self-contained single-file HTML with inlined CSS. Useful for sharing
// without platform access, printing to PDF via browser, or archiving.
// Deterministic — no LLM. Converts the Markdown output to HTML via a
// minimal parser + applies brand colours.

import type { RenderFn, RenderResult } from '../../renderer-registry.types.js';
import { saveArtifact, buildFilename } from '../lib/artifact-storage.js';

export const render: RenderFn = async (_payload, context): Promise<RenderResult> => {
  const markdown = context.markdown ?? '';
  if (!markdown.trim()) throw new Error('No markdown content available for standalone HTML');

  const html = buildHtml({
    title: context.session.title,
    markdown,
    brand: context.brand_template,
  });

  const filename = buildFilename('{module_id}-{timestamp}.{file_type}', {
    module_id: context.session.module_id,
    renderer_id: 'standalone-html',
    file_type: 'html',
  });
  const saved = await saveArtifact({ sessionId: context.session.id, filename, content: html });

  return {
    file_path: saved.rel_path,
    file_type: 'html',
    mime_type: 'text/html; charset=utf-8',
    file_size_bytes: saved.size_bytes,
    metadata: { title: context.session.title, word_count: markdown.split(/\s+/).filter(Boolean).length },
    validation: { valid: true },
  };
};

interface BuildHtmlInput {
  title: string;
  markdown: string;
  brand?: { primary_color?: string; accent_color?: string; font_family?: string } | undefined;
}

function buildHtml({ title, markdown, brand }: BuildHtmlInput): string {
  const primary = brand?.primary_color ?? '#0D7D6C';
  const accent = brand?.accent_color ?? '#1BA882';
  const font = brand?.font_family ?? 'system-ui, -apple-system, Segoe UI, sans-serif';
  const body = markdownToHtml(markdown);
  const escapedTitle = escapeHtml(title);

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${escapedTitle}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  :root {
    --fg: #222;
    --muted: #666;
    --primary: ${primary};
    --accent: ${accent};
    --border: #e5e5e5;
  }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; background: #fff; color: var(--fg); font-family: ${font}; line-height: 1.6; }
  main { max-width: 860px; margin: 0 auto; padding: 48px 32px; }
  header { border-bottom: 3px solid var(--primary); padding-bottom: 16px; margin-bottom: 32px; }
  header h1 { margin: 0 0 4px; font-size: 28px; color: var(--primary); }
  header .meta { color: var(--muted); font-size: 13px; }
  h1 { font-size: 22px; margin-top: 32px; color: var(--primary); }
  h2 { font-size: 18px; margin-top: 28px; color: var(--fg); border-bottom: 1px solid var(--border); padding-bottom: 4px; }
  h3 { font-size: 16px; margin-top: 20px; color: var(--fg); }
  p  { margin: 12px 0; }
  ul, ol { margin: 12px 0; padding-left: 24px; }
  li { margin: 4px 0; }
  strong { color: var(--fg); }
  code { background: #f4f4f4; padding: 1px 5px; border-radius: 3px; font-size: 0.9em; }
  pre { background: #f7f7f7; padding: 12px; border-radius: 6px; overflow-x: auto; font-size: 0.85em; border-left: 3px solid var(--accent); }
  blockquote { border-left: 3px solid var(--accent); padding: 4px 12px; color: var(--muted); margin: 16px 0; background: #fafafa; }
  table { border-collapse: collapse; width: 100%; margin: 16px 0; font-size: 0.92em; }
  th, td { border: 1px solid var(--border); padding: 6px 10px; text-align: left; }
  th { background: #f7f7f7; font-weight: 600; }
  hr { border: none; border-top: 1px solid var(--border); margin: 24px 0; }
  a { color: var(--primary); }
  footer { margin-top: 64px; padding-top: 16px; border-top: 1px solid var(--border); color: var(--muted); font-size: 11px; text-align: center; }
  @media print {
    main { padding: 16px; max-width: none; }
    h1, h2, h3 { page-break-after: avoid; }
    pre, blockquote, table { page-break-inside: avoid; }
  }
</style>
</head>
<body>
<main>
  <header>
    <h1>${escapedTitle}</h1>
    <div class="meta">Generated by ANTON · ${new Date().toISOString().slice(0, 10)}</div>
  </header>
${body}
  <footer>Exported from ANTON — standalone HTML renderer</footer>
</main>
</body>
</html>
`;
}

/**
 * Minimal Markdown → HTML. Covers the subset emitted by ANTON modules:
 * headings (#/##/###), bold (**), italic (*), inline code, fenced code,
 * bullet + numbered lists, blockquotes, horizontal rules, tables,
 * paragraphs. Not a full CommonMark implementation — but deterministic
 * and dependency-free.
 */
function markdownToHtml(md: string): string {
  const lines = md.split(/\r?\n/);
  const out: string[] = [];
  let i = 0;

  function consumeFenced(): boolean {
    const m = /^```(\w+)?/.exec(lines[i] ?? '');
    if (!m) return false;
    i++;
    const codeLines: string[] = [];
    while (i < lines.length && !/^```/.test(lines[i])) { codeLines.push(lines[i]); i++; }
    if (i < lines.length) i++; // consume closing fence
    out.push(`<pre><code>${escapeHtml(codeLines.join('\n'))}</code></pre>`);
    return true;
  }

  function consumeTable(): boolean {
    const header = lines[i];
    const sep = lines[i + 1];
    if (!/^\|/.test(header) || !sep || !/^\|?[\s:-]+\|/.test(sep)) return false;
    const split = (ln: string) => ln.replace(/^\||\|$/g, '').split('|').map(c => c.trim());
    const head = split(header);
    i += 2;
    const rows: string[][] = [];
    while (i < lines.length && /^\|/.test(lines[i])) { rows.push(split(lines[i])); i++; }
    let html = '<table><thead><tr>';
    for (const h of head) html += `<th>${renderInline(h)}</th>`;
    html += '</tr></thead><tbody>';
    for (const r of rows) {
      html += '<tr>';
      for (const c of r) html += `<td>${renderInline(c)}</td>`;
      html += '</tr>';
    }
    html += '</tbody></table>';
    out.push(html);
    return true;
  }

  function consumeList(): boolean {
    const line = lines[i];
    const isBullet = /^\s*[-*+]\s+/.test(line);
    const isNumbered = /^\s*\d+\.\s+/.test(line);
    if (!isBullet && !isNumbered) return false;
    const tag = isBullet ? 'ul' : 'ol';
    const items: string[] = [];
    while (i < lines.length && ((isBullet && /^\s*[-*+]\s+/.test(lines[i])) || (!isBullet && /^\s*\d+\.\s+/.test(lines[i])))) {
      items.push(lines[i].replace(/^\s*([-*+]|\d+\.)\s+/, ''));
      i++;
    }
    out.push(`<${tag}>${items.map(it => `<li>${renderInline(it)}</li>`).join('')}</${tag}>`);
    return true;
  }

  function consumeBlockquote(): boolean {
    if (!/^>\s?/.test(lines[i])) return false;
    const content: string[] = [];
    while (i < lines.length && /^>\s?/.test(lines[i])) {
      content.push(lines[i].replace(/^>\s?/, ''));
      i++;
    }
    out.push(`<blockquote>${content.map(l => `<p>${renderInline(l)}</p>`).join('')}</blockquote>`);
    return true;
  }

  while (i < lines.length) {
    const line = lines[i];
    if (/^\s*$/.test(line)) { i++; continue; }
    if (/^---+$/.test(line)) { out.push('<hr>'); i++; continue; }
    if (/^#{1,6}\s+/.test(line)) {
      const m = /^(#{1,6})\s+(.*)$/.exec(line)!;
      const level = m[1].length;
      out.push(`<h${level}>${renderInline(m[2])}</h${level}>`);
      i++; continue;
    }
    if (consumeFenced()) continue;
    if (consumeTable())  continue;
    if (consumeList())   continue;
    if (consumeBlockquote()) continue;
    // Paragraph — accumulate until blank line or block break
    const para: string[] = [];
    while (i < lines.length && lines[i] && !/^#{1,6}\s+/.test(lines[i])
           && !/^```/.test(lines[i]) && !/^>\s?/.test(lines[i])
           && !/^\s*[-*+]\s+/.test(lines[i]) && !/^\s*\d+\.\s+/.test(lines[i])
           && !/^---+$/.test(lines[i]) && !/^\|/.test(lines[i])) {
      para.push(lines[i]); i++;
    }
    if (para.length) out.push(`<p>${renderInline(para.join(' '))}</p>`);
  }
  return out.join('\n');
}

function renderInline(s: string): string {
  let out = escapeHtml(s);
  // code `…` first so its contents don't get formatted
  out = out.replace(/`([^`]+)`/g, (_, c) => `<code>${c}</code>`);
  // bold **…** before italic *…* so ** doesn't get swallowed by *
  out = out.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
  out = out.replace(/\*([^*]+)\*/g, '<em>$1</em>');
  // links [text](url)
  out = out.replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" rel="noopener">$1</a>');
  return out;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
          .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}
