/**
 * blueprint-skills.test.ts — the FCP blueprint library as ANTON skills
 * (server/skills/fcp-bp-*, generated by scripts/build-blueprint-skills.ts).
 *
 * What this pins:
 *   1. LOAD — all fourteen skills reach the synchronous resolver with their
 *      `blueprint` metadata; a skill.json without that block, or with a
 *      malformed one, still loads (the extension is backwards-compatible).
 *   2. DRAFTS — exactly the four draft blueprints say so in name and description.
 *   3. FIRM-NEUTRAL — no generated text names the firm that wrote the library.
 *      The block list is kept as SHA-256 hashes of lower-case words and short
 *      phrases, so this public repo does not carry the names it guards against.
 *   4. PLACEHOLDERS — every {{name}} a skill uses is explained in its own
 *      Placeholders section, and none is malformed.
 *   5. SCORES — every skill opens with the scoring boundary; a blueprint never
 *      changes how a score is computed.
 *   6. SUGGEST ONLY — module.json `recommendedSkills` and the skills'
 *      `recommendedFor` agree; no module default attaches a blueprint skill;
 *      only a user-selected blueprint format does.
 *   7. FORMATS — the existing 46 output formats are byte-identical to
 *      origin/main; the five blueprint layouts follow the blueprint rules.
 * The no-skill prompt equality for every module is in no-skill-prompt-baseline.test.ts.
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { describe, it, expect, beforeAll } from 'vitest';
import {
  BLUEPRINT_FORMAT_SKILLS,
  getAutoAttachSkillIds,
  getSkillById,
  parseSkillBlueprintMeta,
  preloadDiskSkills,
  resolveSkills,
} from '../../server/services/skills-manager.js';
import { scanTextForInjection } from '../../server/services/anton-injection-scan.js';
import { getAllModules } from '../../server/services/module-loader.js';
import { OUTPUT_FORMATS } from '../../src/lib/output-format-definitions.js';

const REPO = path.resolve(__dirname, '..', '..');
const SKILLS_DIR = path.join(REPO, 'server', 'skills');
const PACK_ENTITIES = path.join(REPO, 'data', 'knowledge-packs', 'fcp-blueprint-references', 'entities.json');

const DRAFT_SLUGS = ['sanctions-risk-assessment', 'abc-risk-assessment', 'fraud-risk-assessment', 'compliance-review-report'];
const STABLE_SLUGS = [
  'aml-ctf-risk-assessment', 'gap-analysis', 'model-documentation', 'model-validation-report', 'proposal',
  'firm-and-team-presentation', 'project-plans-and-governance', 'governing-documents', 'training-and-presentations',
];
const ALL_IDS = ['fcp-bp-house-standards', ...[...DRAFT_SLUGS, ...STABLE_SLUGS].map((s) => `fcp-bp-${s}`)];

/**
 * SHA-256 of lower-case words / phrases (NFC) that must never appear in a
 * generated text: the issuing firm's brand, domain, legal name, former names
 * and street address, as they appear in the library's firm profile (which is
 * never read by the generator).
 */
const BLOCKED_SHA256 = new Set([
  'a9bb69c008560846d59ff84770928f80bf86e5194cb8930e0bc6842f6becf706',
  'f10fedbcbb473f703d61d9a0df0c30ce1fed06e360affab4ac88e67b01fd7b86',
  '9f11991260b0a5d1a9a8db2ba08942d20892ea8fb0b8ac4521afff7e3511582a',
  '462ef8b9e205775f789b24a7645026008f33aec3439b00f02ed77921728dc989',
  '580f9fe3c65228ec8b0b398f09a449413bef7676d7d3480e0086f4cfd7682971',
  '41e08bf371cf74ff88988d59138a0c1ba2f6753e81fc596727341ba3b55e31bb',
]);

const sha = (s: string) => crypto.createHash('sha256').update(s, 'utf8').digest('hex');

/** Every word, dotted-word part and 2-/3-word phrase of a text whose hash is on the block list. */
export function blockedTermsIn(text: string): string[] {
  const words = text.normalize('NFC').toLowerCase().split(/[^\p{L}\p{N}.]+/u)
    .map((w) => w.replace(/^\.+|\.+$/g, ''))
    .filter(Boolean);
  const hits = new Set<string>();
  for (let i = 0; i < words.length; i++) {
    const grams = [words[i], ...words[i].split('.'), words.slice(i, i + 2).join(' '), words.slice(i, i + 3).join(' ')];
    for (const g of grams) if (g && BLOCKED_SHA256.has(sha(g))) hits.add(`hash:${sha(g).slice(0, 12)} near "${words.slice(Math.max(0, i - 3), i).join(' ')} …"`);
  }
  return [...hits];
}

function readSkill(id: string): { json: Record<string, unknown>; content: string } {
  const dir = path.join(SKILLS_DIR, id);
  return {
    json: JSON.parse(fs.readFileSync(path.join(dir, 'skill.json'), 'utf8')) as Record<string, unknown>,
    content: fs.readFileSync(path.join(dir, 'skill-content.md'), 'utf8'),
  };
}

function moduleRecommendations(): Map<string, string[]> {
  const out = new Map<string, string[]>();
  const areas = path.join(REPO, 'server', 'areas');
  for (const area of fs.readdirSync(areas)) {
    const modulesDir = path.join(areas, area, 'modules');
    if (!fs.existsSync(modulesDir)) continue;
    for (const mod of fs.readdirSync(modulesDir)) {
      const file = path.join(modulesDir, mod, 'module.json');
      if (!fs.existsSync(file)) continue;
      const cfg = JSON.parse(fs.readFileSync(file, 'utf8')) as { id?: string; recommendedSkills?: unknown };
      if (Array.isArray(cfg.recommendedSkills)) out.set(cfg.id ?? mod, cfg.recommendedSkills.map(String));
    }
  }
  return out;
}

beforeAll(async () => {
  await preloadDiskSkills();
});

describe('load and validate', () => {
  it('exactly the fourteen fcp-bp-* skills are on disk, each folder named after its id', () => {
    const dirs = fs.readdirSync(SKILLS_DIR).filter((d) => d.startsWith('fcp-bp-')).sort();
    expect(dirs).toEqual([...ALL_IDS].sort());
    for (const id of ALL_IDS) expect(readSkill(id).json.id).toBe(id);
  });

  it('each one resolves from disk with its prompt and a valid blueprint block', () => {
    for (const id of ALL_IDS) {
      const skill = getSkillById(id);
      expect(skill, id).toBeDefined();
      expect(skill?.source).toBe('disk');
      expect(skill?.category).toBe('methodology');
      expect(skill?.prompt.length, id).toBeGreaterThan(20_000);
      expect(skill?.blueprint?.library).toBe('fcp-blueprint-library');
      expect(resolveSkills([id])).toBe(skill?.prompt);
    }
  });

  it('a skill.json without a blueprint block loads as before (the 23 older disk skills)', () => {
    const sg = getSkillById('jurisdiction-sg-mas');
    expect(sg?.source).toBe('disk');
    expect(sg?.blueprint).toBeUndefined();
  });

  it('parseSkillBlueprintMeta accepts the generated blocks and refuses malformed ones', () => {
    const good = readSkill('fcp-bp-gap-analysis').json.blueprint;
    expect(parseSkillBlueprintMeta(good)?.slug).toBe('gap-analysis');
    expect(parseSkillBlueprintMeta(undefined)).toBeNull();
    expect(parseSkillBlueprintMeta('gap-analysis')).toBeNull();
    expect(parseSkillBlueprintMeta({ ...(good as object), status: 'final' })).toBeNull();
    expect(parseSkillBlueprintMeta({ ...(good as object), recommendedFor: 'gap-analysis' })).toBeNull();
    expect(parseSkillBlueprintMeta({ ...(good as object), references: null })).toBeNull();
  });

  it('every reference catalogue is either inlined in the skill or in the knowledge pack', () => {
    const entities = JSON.parse(fs.readFileSync(PACK_ENTITIES, 'utf8')) as Array<{ entity_id: string; metadata?: { file?: string; blueprint?: string; kind?: string } }>;
    const packed = new Set(entities.filter((e) => e.metadata?.kind === 'catalogue').map((e) => `${e.metadata?.blueprint}/${e.metadata?.file}`));
    for (const id of ALL_IDS.filter((x) => x !== 'fcp-bp-house-standards')) {
      const meta = getSkillById(id)!.blueprint!;
      for (const f of meta.references.inlined) expect(getSkillById(id)!.prompt, `${id} inlines ${f}`).toContain(`Reference catalogue: ${f}`);
      for (const f of meta.references.inPack) expect(packed.has(`${meta.slug}/${f}`), `${meta.slug}/${f} in pack`).toBe(true);
      if (meta.references.inPack.length > 0) expect(meta.references.knowledgePack).toBe('fcp-blueprint-references');
    }
  });
});

describe('drafts are visible as drafts', () => {
  it('exactly the four draft blueprints carry status draft, "[DRAFT]" in the name and "DRAFT" first in the description', () => {
    for (const slug of DRAFT_SLUGS) {
      const skill = getSkillById(`fcp-bp-${slug}`)!;
      expect(skill.blueprint?.status, slug).toBe('draft');
      expect(skill.name).toMatch(/^FCP blueprint \[DRAFT\]: /);
      expect(skill.description).toMatch(/^DRAFT – needs team input/);
      expect(skill.prompt).toContain('## Draft status');
      expect(skill.tags).toContain('draft');
    }
    for (const slug of STABLE_SLUGS) {
      const skill = getSkillById(`fcp-bp-${slug}`)!;
      expect(skill.blueprint?.status, slug).toBe('stable');
      expect(skill.name).not.toContain('DRAFT');
      expect(skill.prompt).not.toContain('## Draft status');
    }
  });
});

describe('firm-neutral text', () => {
  const texts = (): Array<[string, string]> => [
    ...ALL_IDS.flatMap((id): Array<[string, string]> => [[`${id}/skill-content.md`, readSkill(id).content], [`${id}/skill.json`, JSON.stringify(readSkill(id).json)]]),
    ['fcp-blueprint-references/entities.json', fs.readFileSync(PACK_ENTITIES, 'utf8')],
  ];

  it('no generated skill or pack text contains a blocked firm name, domain or address', () => {
    const hits = texts().flatMap(([file, text]) => blockedTermsIn(text).map((h) => `${file}: ${h}`));
    expect(hits).toEqual([]);
  });

  it('nothing points at the firm profiles or the open-decisions list', () => {
    for (const [file, text] of texts()) {
      expect(text, file).not.toMatch(/open-decisions|_core\/profiles/);
    }
  });

  it('negative control: the check fires on a blocked word and on a blocked phrase split across punctuation', () => {
    // The probes are assembled from fragments so this file does not spell them out.
    const brand = ['adv', 'isense'].join('');
    expect(blockedTermsIn(`Prepared by ${brand[0].toUpperCase()}${brand.slice(1)} for the client.`).length).toBe(1);
    expect(blockedTermsIn(`See www.${brand}.com.`).length).toBeGreaterThan(0);
    expect(blockedTermsIn(`formerly ${['Financial', 'Compliance', 'Group'].join(' ')}`).length).toBe(1);
    expect(blockedTermsIn('Prepared by {{firm_name}} for {{client_name}}.')).toEqual([]);
  });
});

describe('placeholders', () => {
  it('every {{name}} a skill uses is explained in its own Placeholders section', () => {
    for (const id of ALL_IDS) {
      const { content } = readSkill(id);
      const used = [...new Set([...content.matchAll(/\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g)].map((m) => m[1]))];
      if (used.length === 0) continue;
      const idx = content.lastIndexOf('\n## Placeholders\n');
      expect(idx, `${id} has a Placeholders section`).toBeGreaterThan(0);
      const section = content.slice(idx);
      for (const name of used) expect(section, `${id}: {{${name}}}`).toContain(`\`{{${name}}}\``);
    }
  });

  it('no placeholder is malformed (an opening {{ always closes on the same line)', () => {
    for (const id of ALL_IDS) {
      const { content } = readSkill(id);
      const open = (content.match(/\{\{/g) ?? []).length;
      const closed = (content.match(/\{\{[^{}\n]*\}\}/g) ?? []).length;
      expect(closed, id).toBe(open);
    }
  });
});

describe('scores are never changed by a blueprint', () => {
  it('every skill opens with the scoring boundary, before any method or risk-language text', () => {
    for (const id of ALL_IDS) {
      const { content } = readSkill(id);
      const boundary = content.indexOf('## Scoring boundary (ANTON rule — read first)');
      expect(boundary, id).toBeGreaterThan(0);
      expect(content.indexOf('It never changes how a score is computed.')).toBeGreaterThan(boundary);
      const method = content.indexOf('## Method and quality bar');
      if (method >= 0) expect(boundary).toBeLessThan(method);
      const risk = content.indexOf('## Shared risk language');
      if (risk >= 0) {
        expect(boundary).toBeLessThan(risk);
        expect(content.slice(risk, risk + 1200)).toContain('It is not an instruction to compute anything');
      }
    }
  });

  it('only the four risk-assessment skills carry the full shared risk language', () => {
    const withRisk = ALL_IDS.filter((id) => readSkill(id).content.includes('## Shared risk language'));
    expect(withRisk.sort()).toEqual(['fcp-bp-abc-risk-assessment', 'fcp-bp-aml-ctf-risk-assessment', 'fcp-bp-fraud-risk-assessment', 'fcp-bp-sanctions-risk-assessment']);
  });

  it('no skill text trips the bundle injection scan (a finding would block its import)', () => {
    for (const id of ALL_IDS) expect(scanTextForInjection(readSkill(id).content, id), id).toEqual([]);
  });
});

describe('recommendedSkills only suggests', () => {
  it('module.json recommendedSkills and the skills\' recommendedFor agree, both ways', () => {
    const recs = moduleRecommendations();
    for (const id of ALL_IDS) {
      const declared = getSkillById(id)!.blueprint!.recommendedFor;
      const actual = [...recs.entries()].filter(([, ids]) => ids.includes(id)).map(([mod]) => mod).sort();
      expect(actual, id).toEqual([...declared].sort());
    }
    // Recommendations exist for every deliverable blueprint (the house standards ride with the formats).
    for (const id of ALL_IDS.filter((x) => x !== 'fcp-bp-house-standards')) expect(getSkillById(id)!.blueprint!.recommendedFor.length, id).toBeGreaterThan(0);
  });

  it('no module default attaches a blueprint skill: no default format is a blueprint layout, and the default formats auto-attach none', async () => {
    const modules = await getAllModules();
    expect(modules.length).toBeGreaterThan(500);
    for (const mod of modules) {
      const formats = (mod.defaults?.outputFormats ?? []) as string[];
      expect(formats.filter((f) => f.startsWith('bp-')), mod.id).toEqual([]);
      expect(getAutoAttachSkillIds(formats).filter((s) => s.startsWith('fcp-bp-')), mod.id).toEqual([]);
    }
  });

  it('a blueprint layout the user selects attaches its blueprint skill and the house standards', () => {
    const paired = ALL_IDS.map((id) => getSkillById(id)!.blueprint!).filter((b) => b.pairedOutputFormat);
    expect(Object.keys(BLUEPRINT_FORMAT_SKILLS).sort()).toEqual(paired.map((b) => b.pairedOutputFormat!).sort());
    for (const b of paired) {
      expect(getAutoAttachSkillIds([b.pairedOutputFormat!])).toEqual(expect.arrayContaining([`fcp-bp-${b.slug}`, 'fcp-bp-house-standards']));
    }
  });
});

describe('output formats', () => {
  const BP_FORMATS = ['bp-gap-report', 'bp-bwra-report', 'bp-model-validation-report', 'bp-compliance-review-report', 'bp-governing-document'];

  it('the 46 existing formats are byte-identical to origin/main 692e7f2b', () => {
    const existing = OUTPUT_FORMATS.filter((f) => !f.id.startsWith('bp-'));
    expect(existing.length).toBe(46);
    expect(sha(JSON.stringify(existing))).toBe('3d5d79ea171c4143a70773bfa85d0ff7d04edd16c73701058e144001e4fb5bdc');
  });

  it('the five blueprint layouts exist once each and every one is paired with a skill', () => {
    for (const id of BP_FORMATS) {
      expect(OUTPUT_FORMATS.filter((f) => f.id === id).length, id).toBe(1);
      expect(BLUEPRINT_FORMAT_SKILLS[id], id).toBeDefined();
    }
  });

  it('the blueprint layouts follow the blueprint rules, not the gap-scoring-matrix ones', () => {
    for (const id of BP_FORMATS) {
      const text = OUTPUT_FORMATS.find((f) => f.id === id)!.promptInstruction;
      expect(text, id).toMatch(/(used|report them) (exactly )?as given/);
      expect(text, id).toContain('[DATA NEEDED: …]');
      expect(text, id).not.toMatch(/Fully compliant/); // the old format's label; the rule below says never write it
      // Never told to produce an averaged or total score ("do not calculate … total scores" is the rule itself).
      expect(text, id).not.toMatch(/\b(include|show|give|add|compute|report)\b[^.\n]{0,40}\b(average|total) score/i);
    }
    const gap = OUTPUT_FORMATS.find((f) => f.id === 'bp-gap-report')!.promptInstruction;
    expect(gap).toContain('no apparent deficiencies identified');
    expect(gap).toMatch(/do not calculate averages/);
    expect(OUTPUT_FORMATS.find((f) => f.id === 'bp-model-validation-report')!.promptInstruction).toMatch(/worst result.*no averaging/s);
    expect(OUTPUT_FORMATS.find((f) => f.id === 'bp-compliance-review-report')!.promptInstruction).toMatch(/DRAFT, NEEDS TEAM INPUT/);
  });
});
