/**
 * DemoBanner — the standing notice on a public demo server (DEMO_MODE=true),
 * on the login page and in the app. It cannot be dismissed. It tells the
 * visitor at the first interaction that the answers are generated by AI
 * (AI Act Art. 50(1)), which service and country the text goes to, not to
 * enter personal or client data, and when accounts are deleted; with links
 * to the privacy notice and the demo terms (privacy review G10). The model
 * and the route are the launch configuration's, as in the privacy notice.
 * Renders nothing on an ordinary server.
 */
import { useEffect } from 'react';
import { AlertTriangle } from 'lucide-react';
import { useDemoStore } from '@/stores/useDemoStore';

interface DemoBannerProps {
  /** 'light' on the white login page, 'app' inside the themed layout. */
  variant?: 'app' | 'light';
}

export default function DemoBanner({ variant = 'app' }: DemoBannerProps) {
  const { config, load } = useDemoStore();
  useEffect(() => { void load(); }, [load]);
  if (!config.demoMode) return null;

  const tone = variant === 'light'
    ? 'border-amber-300 bg-amber-50 text-amber-900'
    : 'border-adv-gold/40 bg-adv-gold/15 text-adv-off-white';
  const link = variant === 'light' ? 'text-amber-900 underline hover:text-amber-700' : 'text-adv-gold underline hover:text-adv-off-white';

  return (
    <div role="note" aria-label="Demo notice" className={`flex items-start gap-2 border-b px-4 py-2 text-sm leading-snug ${tone}`}>
      <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" aria-hidden="true" />
      <p>
        <strong>Demo:</strong> answers are generated by AI (GLM 5.3 Flash, via OpenRouter, USA) and can be wrong.{' '}
        <strong>Don&apos;t enter personal or client data.</strong>{' '}
        Accounts expire after {config.retentionDays} days and are then deleted.{' '}
        <a href={config.privacyPath} className={link}>Privacy notice</a>
        {' · '}
        <a href={config.termsPath} className={link}>Terms</a>
      </p>
    </div>
  );
}
