// ── Renderer: Board Deck (3-5 slide PPTX) ───────────────────────────────
//
// Condensed board deck for analytic_report / gap_analysis / scorecard.
// Uses an LLM pass to distil each slide's content, then renders via
// pptxgenjs with brand colours + speaker notes.
//
// Five slides:
//   1. Title              — report title + one-sentence framing
//   2. Bottom line        — 3 bullet key takeaways
//   3. Findings / Status  — bullets (analytic_report: findings;
//                           gap_analysis: top scored gaps;
//                           scorecard: status by category)
//   4. Recommendations    — bullets (analytic_report + gap_analysis)
//                           OR trend/actions (scorecard)
//   5. Next decision      — the single decision being asked of the board

import PptxGenJS from 'pptxgenjs';
import type { RenderFn, RenderResult } from '../../renderer-registry.types.js';
import { callChat } from '../../provider-router.js';
import { saveArtifact, buildFilename } from '../lib/artifact-storage.js';
import { wrapUntrustedContent, INJECTION_GUARD_SUFFIX } from '../lib/prompt-injection-guard.js';

const MODEL = 'claude-sonnet-4-6';
const MAX_TOKENS = 3_500;
const TIMEOUT_MS = 75_000;

interface DeckSlideSpec {
  title: string;
  bullets: string[];
  speaker_notes?: string;
}
interface DeckSpec {
  deck_title: string;
  framing: string;
  slides: DeckSlideSpec[];
  next_decision: string;
}

const SYSTEM_PROMPT = `You produce board-ready slide content. Your output is JSON only.

OUTPUT: a single \`json\` block with this shape (no prose outside):
\`\`\`json
{
  "deck_title": "<report title>",
  "framing": "<one sentence: why this is on the agenda>",
  "slides": [
    { "title": "Bottom line",        "bullets": ["...", "...", "..."],        "speaker_notes": "..." },
    { "title": "Findings",           "bullets": ["...", "...", "...", "..."], "speaker_notes": "..." },
    { "title": "Recommendations",    "bullets": ["...", "...", "..."],        "speaker_notes": "..." }
  ],
  "next_decision": "<single sentence: the decision you want from the board>"
}
\`\`\`

RULES:
- Each bullet ≤ 15 words, plain declarative voice, no hedging.
- Numbers, dates, regulation names preserved verbatim from the source.
- Speaker notes: 2-3 sentences per slide with the evidence behind each bullet.
- Do NOT invent data not in the source.
- Do NOT produce more than 5 slide specs (title slide is added by the renderer).`;

export const render: RenderFn = async (payload, context): Promise<RenderResult> => {
  const markdown = context.markdown ?? '';
  if (!markdown.trim()) throw new Error('No markdown content available for board deck');

  // Ask LLM for the distilled deck spec
  const userPrompt = `Report title: ${context.session.title}\nContent type: ${payload.content_type}\n\n${wrapUntrustedContent(markdown)}${INJECTION_GUARD_SUFFIX}`;
  const chat = await Promise.race([
    callChat({ model: MODEL, system: SYSTEM_PROMPT, messages: [{ role: 'user', content: userPrompt }], maxTokens: MAX_TOKENS, temperature: 0.2 }),
    new Promise<never>((_, reject) => setTimeout(() => reject(new Error(`board-deck timed out after ${TIMEOUT_MS}ms`)), TIMEOUT_MS)),
  ]);

  const spec = parseDeckSpec(chat.text);
  if (!spec) throw new Error('LLM did not return a usable deck JSON');

  // Build PPTX
  const primary = context.brand_template?.primary_color ?? '0D7D6C';
  const accent = context.brand_template?.accent_color ?? '1BA882';
  const pptx = new PptxGenJS();
  pptx.layout = 'LAYOUT_WIDE';

  // Slide 1 — Title
  {
    const s = pptx.addSlide();
    s.background = { color: 'FFFFFF' };
    s.addShape('rect', { x: 0, y: 4.2, w: 13.3, h: 0.12, fill: { color: normaliseHex(primary) } });
    s.addText(spec.deck_title, { x: 0.7, y: 2.4, w: 12, h: 1.2, fontSize: 36, bold: true, color: '111111' });
    s.addText(spec.framing, { x: 0.7, y: 3.6, w: 12, h: 0.6, fontSize: 16, color: '555555' });
    s.addText(`Generated by ANTON · ${new Date().toISOString().slice(0, 10)}`, { x: 0.7, y: 6.6, w: 12, h: 0.3, fontSize: 10, color: '999999' });
  }

  // Body slides
  for (const slide of spec.slides.slice(0, 5)) {
    const s = pptx.addSlide();
    s.addShape('rect', { x: 0, y: 0, w: 13.3, h: 0.5, fill: { color: normaliseHex(primary) } });
    s.addText(slide.title, { x: 0.5, y: 0.08, w: 12, h: 0.34, fontSize: 20, bold: true, color: 'FFFFFF' });
    const bulletsText = slide.bullets.map(b => ({ text: b, options: { bullet: true } }));
    s.addText(bulletsText, { x: 0.7, y: 0.9, w: 12, h: 5.5, fontSize: 18, color: '222222', paraSpaceAfter: 12 });
    s.addShape('rect', { x: 0, y: 7.1, w: 13.3, h: 0.2, fill: { color: normaliseHex(accent) } });
    if (slide.speaker_notes) s.addNotes(slide.speaker_notes);
  }

  // Final slide — Next decision
  {
    const s = pptx.addSlide();
    s.background = { color: normaliseHex(primary) };
    s.addText('Decision requested', { x: 0.7, y: 1.8, w: 12, h: 0.8, fontSize: 22, color: 'FFFFFF', bold: true });
    s.addText(spec.next_decision, { x: 0.7, y: 3.0, w: 12, h: 2.5, fontSize: 28, color: 'FFFFFF', bold: false, valign: 'top' });
  }

  // Emit
  const buf = await pptx.write({ outputType: 'nodebuffer' }) as Buffer;
  const filename = buildFilename('{module_id}-board-deck-{timestamp}.{file_type}', {
    module_id: context.session.module_id,
    renderer_id: 'board-deck',
    file_type: 'pptx',
  });
  const saved = await saveArtifact({ sessionId: context.session.id, filename, content: buf });

  return {
    file_path: saved.rel_path,
    file_type: 'pptx',
    mime_type: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    file_size_bytes: saved.size_bytes,
    metadata: { model: MODEL, slide_count: 1 + Math.min(5, spec.slides.length) + 1, deck_title: spec.deck_title },
    tokens_consumed: (chat.inputTokens ?? 0) + (chat.outputTokens ?? 0),
    validation: { valid: true },
  };
};

function parseDeckSpec(text: string): DeckSpec | null {
  const re = /```json\s*\n([\s\S]*?)\n```/g;
  let match: RegExpExecArray | null; let last: string | null = null;
  while ((match = re.exec(text)) !== null) last = match[1];
  const raw = (last ?? text).trim();
  try {
    const obj = JSON.parse(raw) as DeckSpec;
    if (!obj?.deck_title || !Array.isArray(obj.slides)) return null;
    // Defensive bounds — prevents the LLM from producing pathologically
    // large slides/bullets that bloat PPTX or hide injected content.
    obj.deck_title = String(obj.deck_title).slice(0, 200);
    obj.framing = String(obj.framing ?? '').slice(0, 500);
    obj.next_decision = String(obj.next_decision ?? '').slice(0, 500);
    obj.slides = obj.slides
      .slice(0, 8)
      .filter(s => s && typeof s.title === 'string' && Array.isArray(s.bullets))
      .map(s => ({
        title: s.title.slice(0, 100),
        bullets: s.bullets.filter(b => typeof b === 'string').map(b => b.slice(0, 500)).slice(0, 12),
        speaker_notes: s.speaker_notes ? String(s.speaker_notes).slice(0, 2000) : undefined,
      }));
    return obj;
  } catch { return null; }
}

function normaliseHex(v: string): string {
  return String(v).replace(/^#/, '').toUpperCase();
}
