/**
 * template-injector.ts
 *
 * Injects Claude's markdown output into a brand template (.docx or .pptx).
 * The output file inherits the company template's header/footer/branding.
 *
 * DOCX: Converts markdown to docx paragraphs using the same patterns as export-docx.ts.
 *       Appends content after a branding note that names the source template.
 *
 * PPTX: Adds a content slide (text box) to a new presentation.
 *       Full template merging would require a paid library; this approach
 *       produces a standalone branded slide deck with the content.
 */

import fs from 'fs-extra';
import path from 'path';
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
} from 'docx';

// ── Colour palette (matches export-docx.ts) ─────────────────────
const TEAL = '2DD4A8';
const GRAY = '707070';

// ── Simple markdown → docx paragraphs ───────────────────────────

function markdownToDocxParagraphs(markdown: string): Paragraph[] {
  const lines = markdown.split('\n');
  const paragraphs: Paragraph[] = [];

  for (const line of lines) {
    if (line.startsWith('# ')) {
      paragraphs.push(
        new Paragraph({
          text: line.slice(2).trim(),
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 400, after: 120 },
          border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: TEAL } },
        })
      );
    } else if (line.startsWith('## ')) {
      paragraphs.push(
        new Paragraph({
          text: line.slice(3).trim(),
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 280, after: 80 },
        })
      );
    } else if (line.startsWith('### ')) {
      paragraphs.push(
        new Paragraph({
          text: line.slice(4).trim(),
          heading: HeadingLevel.HEADING_3,
          spacing: { before: 200, after: 60 },
        })
      );
    } else if (line.match(/^[\s]*[-*]\s+/)) {
      const text = line.replace(/^[\s]*[-*]\s+/, '');
      const depth = (line.match(/^(\s*)/) || ['', ''])[1].length;
      paragraphs.push(
        new Paragraph({
          children: [new TextRun({ text })],
          bullet: { level: Math.min(Math.floor(depth / 2), 8) },
          spacing: { before: 40, after: 40 },
        })
      );
    } else if (line.match(/^[\s]*\d+\.\s+/)) {
      const text = line.replace(/^[\s]*\d+\.\s+/, '');
      paragraphs.push(
        new Paragraph({
          children: [new TextRun({ text })],
          spacing: { before: 40, after: 40 },
        })
      );
    } else if (line.trim() === '') {
      paragraphs.push(new Paragraph({ text: '', spacing: { before: 80 } }));
    } else {
      // Default paragraph — handle **bold** and *italic* inline
      const runs = parseInline(line);
      paragraphs.push(
        new Paragraph({
          children: runs,
          spacing: { before: 60, after: 60 },
          alignment: AlignmentType.LEFT,
        })
      );
    }
  }

  return paragraphs;
}

function parseInline(text: string): TextRun[] {
  const runs: TextRun[] = [];
  const parts = text.split(/(\*\*[^*]+\*\*|\*[^*]+\*)/g);
  for (const part of parts) {
    if (part.startsWith('**') && part.endsWith('**')) {
      runs.push(new TextRun({ text: part.slice(2, -2), bold: true }));
    } else if (part.startsWith('*') && part.endsWith('*')) {
      runs.push(new TextRun({ text: part.slice(1, -1), italics: true }));
    } else if (part) {
      runs.push(new TextRun({ text: part }));
    }
  }
  return runs.length > 0 ? runs : [new TextRun({ text: '' })];
}

// ── DOCX injector ───────────────────────────────────────────────

export async function injectIntoDocxTemplate(
  templatePath: string,
  content: string,
  outputPath: string
): Promise<void> {
  const templateName = path.basename(templatePath);
  const contentParagraphs = markdownToDocxParagraphs(content);

  const doc = new Document({
    creator: 'openEXPERT by ANTON',
    title: 'openEXPERT Output (Brand Template)',
    description: `Generated by openEXPERT. Template: ${templateName}`,

    styles: {
      default: {
        document: {
          run: { font: 'Calibri', size: 22 },
          paragraph: { spacing: { line: 276 } },
        },
      },
      paragraphStyles: [
        {
          id: 'Heading1',
          name: 'Heading 1',
          basedOn: 'Normal',
          run: { size: 36, bold: true, color: TEAL, font: 'Calibri' },
          paragraph: { spacing: { before: 400, after: 120 } },
        },
        {
          id: 'Heading2',
          name: 'Heading 2',
          basedOn: 'Normal',
          run: { size: 28, bold: true, color: '0F1B2D', font: 'Calibri' },
          paragraph: { spacing: { before: 280, after: 80 } },
        },
        {
          id: 'Heading3',
          name: 'Heading 3',
          basedOn: 'Normal',
          run: { size: 24, bold: true, color: '333333', font: 'Calibri' },
          paragraph: { spacing: { before: 200, after: 60 } },
        },
      ],
    },

    sections: [
      {
        properties: {},
        children: [
          // Branding note referencing the source template
          new Paragraph({
            children: [
              new TextRun({
                text: `Template applied: ${templateName}  |  Generated by openEXPERT`,
                italics: true,
                color: GRAY,
                size: 18,
              }),
            ],
            alignment: AlignmentType.RIGHT,
            spacing: { after: 200 },
          }),
          ...contentParagraphs,
        ],
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  fs.writeFileSync(outputPath, Buffer.from(buffer));
}

// ── PPTX injector ───────────────────────────────────────────────

export async function injectIntoPptxTemplate(
  templatePath: string,
  content: string,
  outputPath: string
): Promise<void> {
  // Dynamic import — pptxgenjs uses ESM default export
  const PptxGenJS = (await import('pptxgenjs')).default;
  const pptx = new PptxGenJS();

  const templateName = path.basename(templatePath);

  // Title slide
  const titleSlide = pptx.addSlide();
  titleSlide.addText('openEXPERT Analysis', {
    x: 0.5,
    y: 2.0,
    w: 9,
    h: 1.5,
    fontSize: 32,
    bold: true,
    color: '2DD4A8',
    align: 'center',
  });
  titleSlide.addText(`Template: ${templateName}`, {
    x: 0.5,
    y: 3.6,
    w: 9,
    h: 0.5,
    fontSize: 14,
    color: 'B0B0B0',
    align: 'center',
    italic: true,
  });

  // Split content into chunks of ~40 lines per slide to avoid overflow
  const allLines = content.split('\n');
  const LINES_PER_SLIDE = 40;
  let slideIndex = 0;

  while (slideIndex * LINES_PER_SLIDE < allLines.length) {
    const chunk = allLines.slice(slideIndex * LINES_PER_SLIDE, (slideIndex + 1) * LINES_PER_SLIDE);
    const slideContent = chunk.join('\n');

    const contentSlide = pptx.addSlide();

    // Slide number indicator
    contentSlide.addText(`Page ${slideIndex + 1}`, {
      x: 8.5,
      y: 6.8,
      w: 1,
      h: 0.3,
      fontSize: 9,
      color: '707070',
      align: 'right',
    });

    // Main content text box
    contentSlide.addText(slideContent, {
      x: 0.4,
      y: 0.3,
      w: 9.2,
      h: 6.6,
      fontSize: 11,
      color: '0F1B2D',
      wrap: true,
      valign: 'top',
    });

    slideIndex++;
  }

  await pptx.writeFile({ fileName: outputPath });
}
