-- Migration 057 (PG): Markets table partitioning — INTENTIONALLY A NO-OP.
--
-- Background
-- ----------
-- The original version of this migration tried to convert market_data_raw,
-- market_atoms, market_pattern_detections and market_index_nav_history into
-- RANGE-partitioned tables by renaming each to *_old, creating a new partitioned
-- table, copying data with `INSERT ... SELECT *`, and dropping the old table.
--
-- That version never actually ran successfully anywhere:
--   * The `INSERT ... SELECT *` copies failed immediately with
--     "INSERT has more expressions than target columns" (the new partitioned
--     tables had a different column count/order than the originals).
--   * Even with explicit column lists it could not complete, because the
--     dependent FK constraints (market_atom_sources, market_atom_tags,
--     market_atom_relationships, market_thesis_atoms → market_atoms; and
--     market_atom_sources → market_data_raw) block DROP TABLE, and the new
--     composite primary keys (id, created_at) / (id, fetched_at) can no longer
--     satisfy the single-column FKs the application relies on.
--
-- More importantly, the new partitioned table definitions DROPPED columns that
-- the rest of the system depends on:
--   * market_data_raw lost `published_at`, `content`, `is_processed`
--     — migration 063 builds a UNIQUE index on `published_at`, and several
--       services (market-data-service, market-nav-engine, …) read these columns.
--   * market_atoms lost `subcategory`, `is_active`, `temporal_type`,
--     `valid_from`, `superseded_by`
--     — migration 070 backfills using `subcategory`, and many services filter on
--       `is_active`.
-- Partitioning these tables therefore breaks later migrations and the running app.
--
-- Existing installs already have this migration recorded in schema_migrations
-- (it was marked applied even though the partition swap never happened), so the
-- tables there remain non-partitioned with their full column sets — and the
-- system works. To make a fresh `db:init` reach that exact same, known-good
-- state, this migration is now a deliberate no-op: the markets tables keep their
-- original 049/051 shapes (non-partitioned, all columns intact).
--
-- The JSONB/NUMERIC conversions, GIN indexes and materialized views that used to
-- be split across 056/057 all live in migration 056, which is unaffected.
--
-- If table partitioning is ever revisited, it must be done with a column-complete
-- superset schema, FK-aware handling, and coordinated updates to the downstream
-- migrations and services — not here.

SELECT 1;
